CREATE TABLE movies (
    id                  BIGINT PRIMARY KEY,
    title               TEXT,
    vote_average        NUMERIC,
    vote_count          INTEGER,
    status              TEXT,
    release_date        DATE,
    release_year        INTEGER,
    runtime             INTEGER,
    budget              BIGINT,
    revenue             BIGINT,
    adult               BOOLEAN,
    backdrop_path       TEXT,
    homepage            TEXT,
    imdb_id             TEXT,
    original_language   TEXT,
    original_title      TEXT,
    overview            TEXT,
    popularity          NUMERIC,
    poster_path         TEXT,
    tagline             TEXT,
    overview_sentiment  NUMERIC,
    AverageRating       NUMERIC,
    Poster_Link         TEXT,
    Certificate         TEXT,
    IMDB_Rating         NUMERIC,
    Meta_score          NUMERIC,
    all_combined_keywords TEXT
);
