CREATE TABLE IF NOT EXISTS movies
(
    id                      INTEGER UNIQUE,
    title                   TEXT,
    vote_average            DECIMAL(3, 1),
    vote_count              INTEGER,
    status                  TEXT,
    release_date            DATE,
    revenue                 BIGINT,
    runtime                 INTEGER,
    adult                   BOOLEAN,
    genres                  TEXT,
    overview_sentiment      TEXT,
    cast_members            TEXT,
    crew_members            TEXT,
    genres_list             TEXT,
    keywords                TEXT,
    director_of_photography TEXT,
    producers               TEXT,
    music_composer          TEXT,
    star1                   TEXT,
    star2                   TEXT,
    star3                   TEXT,
    star4                   TEXT,
    writer                  TEXT,
    original_language       TEXT,
    original_title          TEXT,
    popularity              DECIMAL(10, 3),
    budget                  BIGINT,
    tagline                 TEXT,
    production_companies    TEXT,
    production_countries    TEXT,
    spoken_languages        TEXT,
    homepage                TEXT,
    imdb_id                 TEXT,
    tmdb_id                 TEXT,
    video                   BOOLEAN,
    poster_path             TEXT,
    backdrop_path           TEXT,
    release_year            INTEGER,
    director                TEXT,
    certificate             TEXT,
    collection_name         TEXT,
    collection_id           TEXT,
    genres_id               TEXT,
    original_language_code  TEXT,
    overview                TEXT,
    all_combined_keywords   TEXT
);